export function generateReportHTML(report: {
  clientName: string;
  trainerName: string;
  summary: {
    totalSessions: number;
    attended: number;
    cancelled: number;
    noShows: number;
    attendanceRate: number;
    consistencyScore: number;
    firstSession: string | null;
    lastSession: string | null;
  };
  packages: { name: string; total_sessions: number; used_sessions: number; status: string }[];
  recentNotes: { date: string; notes: string }[];
}) {
  const s = report.summary;
  const sinceDate = s.firstSession
    ? new Date(s.firstSession).toLocaleDateString("en-US", { month: "long", year: "numeric" })
    : "";

  const packagesHtml = report.packages.length > 0
    ? `<div class="card"><h3 style="margin:0 0 12px;font-size:14px;">Packages</h3>${report.packages.map((p) => `
        <div style="margin-bottom:8px;">
          <div style="display:flex;justify-content:space-between;font-size:13px;margin-bottom:4px;">
            <span>${p.name}</span><span>${p.used_sessions}/${p.total_sessions}</span>
          </div>
          <div class="bar-bg"><div class="bar-fill" style="width:${(p.used_sessions / p.total_sessions) * 100}%"></div></div>
        </div>`).join("")}</div>`
    : "";

  const notesHtml = report.recentNotes.length > 0
    ? `<div class="card"><h3 style="margin:0 0 12px;font-size:14px;">Recent Notes</h3>${report.recentNotes.map((n) => `
        <div class="note"><div class="note-date">${n.date}</div><div style="font-size:13px;margin-top:2px;">${n.notes}</div></div>`).join("")}</div>`
    : "";

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Progress Report - ${report.clientName}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 500px; margin: 40px auto; padding: 0 20px; color: #18181b; }
  .card { border: 1px solid #e4e4e7; border-radius: 12px; padding: 24px; margin-bottom: 16px; }
  .header { text-align: center; margin-bottom: 24px; }
  .stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin: 16px 0; }
  .stat { background: #f4f4f5; border-radius: 8px; padding: 12px; text-align: center; }
  .stat-value { font-size: 24px; font-weight: 700; }
  .stat-label { font-size: 12px; color: #71717a; }
  .bar-bg { background: #e4e4e7; border-radius: 4px; height: 8px; overflow: hidden; }
  .bar-fill { background: #0f172a; height: 100%; border-radius: 4px; }
  .note { border-left: 3px solid #e4e4e7; padding: 8px 12px; margin: 8px 0; }
  .note-date { font-size: 12px; color: #71717a; }
  .footer { text-align: center; color: #a1a1aa; font-size: 12px; margin-top: 24px; }
</style></head><body>
<div class="header">
  <h1 style="margin:0;font-size:24px;">Progress Report</h1>
  <p style="color:#71717a;margin:4px 0 0;">${report.clientName} &middot; Trained by ${report.trainerName}</p>
  ${sinceDate ? `<p style="color:#a1a1aa;font-size:12px;margin:4px 0 0;">Since ${sinceDate}</p>` : ""}
</div>
<div class="card">
  <div class="stats">
    <div class="stat"><div class="stat-value">${s.attended}</div><div class="stat-label">Sessions</div></div>
    <div class="stat"><div class="stat-value">${s.attendanceRate}%</div><div class="stat-label">Attendance</div></div>
    <div class="stat"><div class="stat-value">${s.consistencyScore}%</div><div class="stat-label">Consistency</div></div>
  </div>
</div>
${packagesHtml}
${notesHtml}
<div class="footer">Generated by FitBook</div>
</body></html>`;
}
